<?php

namespace App\Exceptions;

use App\Exceptions\Transaction\NotAuthorizedTransactionException;
use Doctrine\DBAL\Exception;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Symfony\Component\Translation\Exception\NotFoundResourceException;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * The list of the inputs that are never flashed to the session on validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     */
    public function register(): void
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    public function render($request, Throwable $e)
    {
        if ($e instanceof NotAuthorizedTransactionException) {
            throw new NotFoundResourceException($e->getMessage(), $e->getCode());
        }
        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
